#!/bin/bash
#<filename>    <***FIXME***>
#<path>        <***FIXME***>
#<repo>        https://github.com/dinkumsoftware/dinkum.git
#<copyright>   Copyright (c) 2020 Dinkum Software
#<lic oneline> Apache 2.0 (see end of file)

#<authors> tc tom campbell, www.DinkumSoftware.com

#<history>
#    <***FIXME***>
#</history>

scriptname=$(basename $0)
usage_str="USAGE:"$scriptname"   <***FIXME***>
"

set -e # die on error
set -u # die on unexpandable variable
function usage() {
    echo -n "$usage_str" ;
}

# Parse all cmd line args
# handle the standard ones
OPTIND=1
while getopts h opt; do
    case $opt in
        h)
            usage
            exit 0
            ;;
        *)
            usage | head -1             1>&2
            exit 1
            ;;
    esac
done
shift "$((OPTIND-1))"   # Discard the options and sentinel --

# Handle your command arguments here

# Make sure we ate all the command line arguments
if [ $# -ne 0 ] ; then
    echo "$scriptname: Unknown cmd line arg(s): $*" 1>&2
    usage | head -1                                 1>&2
    exit 1
fi

# Real code starts here




#<lic>
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#</lic>

